name: "Discord Notify (Merge Commit or Manual Trigger)"
description: "Send a Discord message when merge commit is pushed or workflow is manually triggered"

inputs:
  webhook_url:
    description: "Discord webhook URL"
    required: true
  environment:
    description: "Deployment environment name (e.g., int, prod)"
    required: true
  job_status:
    description: "Status of the job: success or failure"
    required: true
  event_name:
    description: "GitHub event name (e.g., push, workflow_dispatch)"
    required: true
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Send Discord Notification
      shell: bash
      run: |
        set -e

        WEBHOOK_URL="${{ inputs.webhook_url }}"
        ENVIRONMENT="${{ inputs.environment }}"
        JOB_STATUS="${{ inputs.job_status }}"
        EVENT_NAME="${{ inputs.event_name }}"
        DEBUG="${{ inputs.debug }}"

        BRANCH="${GITHUB_REF_NAME}"
        REPO="${GITHUB_REPOSITORY}"
        RUN_ID="${GITHUB_RUN_ID}"
        RUN_URL="https://github.com/${REPO}/actions/runs/${RUN_ID}"
        ACTOR="${GITHUB_ACTOR}"
        WORKFLOW_NAME="${GITHUB_WORKFLOW}"
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)

        if [[ "$JOB_STATUS" == "success" ]]; then
          STATUS_TEXT="succeeded"
          COLOR=3066993
        else
          STATUS_TEXT="failed"
          COLOR=15158332
        fi

        if [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
          COMMITS=$(git log --oneline -5 --pretty=format:"• [%h](https://github.com/$REPO/commit/%H) %s" 2>/dev/null || echo "• Unable to fetch commits")
          DESCRIPTION="**$WORKFLOW_NAME:** Manually triggered workflow [#$RUN_ID]($RUN_URL) on branch **$BRANCH** by $ACTOR has $STATUS_TEXT  **Recent Commits:** $COMMITS"

        elif [[ "$EVENT_NAME" == "push" ]]; then
          COMMIT_MSG=$(git log -1 --pretty=%B || echo "")
          if [[ "$COMMIT_MSG" != Merge\ pull\ request* ]]; then
            echo "Not a merge commit. Skipping Discord notification."
            exit 0
          fi
          DESCRIPTION="**$WORKFLOW_NAME:** Merge commit pushed to **$BRANCH** by $ACTOR has $STATUS_TEXT  **Commit Message:** $COMMIT_MSG [View Run]($RUN_URL)"
        else
          echo "Unsupported event: $EVENT_NAME"
          exit 0
        fi

        jq -n --arg actor "$ACTOR" \
              --arg desc "$DESCRIPTION" \
              --arg time "$TIMESTAMP" \
              --argjson color "$COLOR" \
              --arg icon "https://github.com/$ACTOR.png" \
              '{
                embeds: [
                  {
                    color: $color,
                    author: {
                      name: $actor,
                      icon_url: $icon
                    },
                    description: $desc,
                    timestamp: $time,
                    footer: {
                      text: "Github Alerts APP"
                    }
                  }
                ]
              }' > payload.json

        curl -s -X POST -H "Content-Type: application/json" \
          --data @payload.json "$WEBHOOK_URL"

        rm -f payload.json
