name: Reusable Merge & Manual Discord Notify

on:
  workflow_call:
    secrets:
      discord_webhook:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: ./.github/actions/discord-notify
        with:
          webhook_url: ${{ secrets.discord_webhook }}
          environment: ${{ github.ref_name }}
          job_status: ${{ job.status }}
          event_name: ${{ github.event_name }}
